#
# Copyright (C) 2024 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/xiaomi/air
BOARD_VENDOR := xiaomi

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT := generic

# ABI
TARGET_CPU_ABI := arm64-v8a
TARGET_2ND_CPU_ABI := armeabi-v7a

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# ================================
# SOURCE-BUILT GKI KERNEL MODE
# ================================
TARGET_KERNEL_SOURCE := kernel/common/android13-5.15
TARGET_KERNEL_CONFIG := gki_defconfig
TARGET_KERNEL_VERSION := 5.15

BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_KERNEL_IMAGE_NAME := Image

BOARD_USES_VENDOR_BOOT_IMAGE := true
BOARD_BUILD_VENDOR_BOOT_IMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# init_boot (GKI)
BOARD_BUILD_INIT_BOOT_IMAGE := true

BOARD_INCLUDE_RECOVERY_RAMDISK := false
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true

# VINTF
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/vintf/manifest.xml
DEVICE_MATRIX_FILE := $(DEVICE_PATH)/vintf/compatibility_matrix.xml

# A/B OTA
AB_OTA_UPDATER := true

# Dynamic Partitions
BOARD_USES_DYNAMIC_PARTITIONS := true
BOARD_SUPER_PARTITION_SIZE := 7516192768
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := 5554343936
BOARD_MAIN_PARTITION_LIST := system vendor product odm
